name: first

on: [push]

jobs:

  job1:
    runs-on: ubuntu-latest
    name: First job
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Make dummy file
      run: touch ${{ env.FILENAME }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ env.FILENAME }}
        path: .
    env:
      FILENAME: XD.XD
  
