name: first

on: [push]

jobs:

  job1:
    runs-on: ubuntu-latest
    name: First job
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Python Syntax Detection
      uses: cclauss/Find-Python-syntax-errors-action@master
  
